allowBuilds:
  '@prisma/engines': true
  '@prisma/client': true
  '@reown/appkit': true
  '@stellar/stellar-sdk': true
  bigint-buffer: true
  blake-hash: true
  bufferutil: true
  core-js: true
  core-js-pure: true
  keccak: true
  prisma: true
  protobufjs: true
  secp256k1: true
  sharp: true
  tiny-secp256k1: true
  unrs-resolver: true
  usb: false
  utf-8-validate: true
  esbuild: true
